-- CEX success controls for the lifecycle comparison surface.
-- These are not a pooled ranking: every metric retains its issuer-specific
-- definition, reporting period, source, and comparison key.

INSERT OR REPLACE INTO successful_exchanges
  (slug, type, venue_type, name, launched, primary_chain, status, metric_label,
   metric_type, metric_unit, metric, why_successful, outlook, profile, sources, updated_at)
VALUES
  ('coinbase','cex','exchange','Coinbase','2012',NULL,'successful_established','2025 reported trading volume','platform_trading_volume_annual','USD',1221000000000,
   'A public-company control: the cited 2025 filing reports a live multi-product trading platform and $1.221T of reported trading volume. The dossier treats the figure as Coinbase''s defined metric, not market-wide spot volume.',
   'Success does not remove exposure to transaction-fee cyclicality, regulatory change, custody risk, or a reporting-definition change. Recheck issuer reporting and comparable live spot data on the scheduled review.',
   '{"operational_model":"Custodial multi-product exchange, brokerage, institutional platform, and infrastructure provider; this case scopes the centralized venue rather than Base or self-custodial wallet products.","chains":[],"token":{"launched":false,"symbol":null,"role":"No exchange token is asserted from the reviewed issuer sources."},"metrics":{"platform_trading_volume_annual_usd":1221000000000,"period_end":"2025-12-31","source_url":"https://www.sec.gov/Archives/edgar/data/1679788/000167978826000015/coin-20251231.htm","method_note":"Coinbase''s reported annual Trading Volume; not a direct substitute for third-party spot-only exchange volume."},"success_factors":["regulated_public_company_disclosure","retail_and_institutional_distribution","multi_product_revenue","custody_and_infrastructure"],"risks":["transaction_fee_cyclicality","regulatory_change","custody_and_operational_risk","metric_definition_change"],"synthesis":"Coinbase is a success control because a public filing establishes operating continuity and material reported volume. The causal explanation remains a hypothesis: distribution, compliance posture, and product breadth are plausible mechanisms, not proven by the volume figure alone."}',
   '[{"title":"Coinbase 2025 Form 10-K","url":"https://www.sec.gov/Archives/edgar/data/1679788/000167978826000015/coin-20251231.htm"},{"title":"Coinbase 2025 shareholder letter filed with the SEC","url":"https://www.sec.gov/Archives/edgar/data/1679788/000167978826000011/q425shareholderletter.htm"}]','2026-07-29'),
  ('kraken','cex','exchange','Kraken','2011',NULL,'successful_established','2025 platform transaction volume','platform_transaction_volume_annual','USD',2000000000000,
   'Kraken''s published 2025 financial update reports $2.0T of platform transaction volume, $48.2B in assets, and 5.7M funded accounts. These issuer-reported measures establish a scaled, active control but are not interchangeable with spot-only venue volume.',
   'Maintain the distinction between platform transaction volume, customer assets, and independently measured liquidity; regulation, custody, and fee compression remain material.',
   '{"operational_model":"Custodial centralized exchange and financial-services platform serving retail and institutional customers.","chains":[],"token":{"launched":false,"symbol":null,"role":"No exchange token is asserted from the reviewed financial update."},"metrics":{"platform_transaction_volume_annual_usd":2000000000000,"assets_usd":48200000000,"funded_accounts":5700000,"period_end":"2025-12-31","source_url":"https://blog.kraken.com/news/kraken-2025-financials","method_note":"Issuer-reported platform transaction volume; do not pool with spot-only or derivatives-only metrics."},"success_factors":["long_operating_history","retail_and_institutional_distribution","asset_custody_scale","proof_of_reserves_reporting"],"risks":["custody_and_counterparty_risk","regulatory_change","fee_compression","issuer_reported_metric_scope"],"synthesis":"Kraken is a scale-and-survival control with disclosed 2025 activity, assets, and funded accounts. The reported measures support status and scale, not a claim that any one product feature caused the outcome."}',
   '[{"title":"Kraken 2025 financial update","url":"https://blog.kraken.com/news/kraken-2025-financials"}]','2026-07-29'),
  ('binance','cex','exchange','Binance','2017',NULL,'successful_established','2025 all-product trading volume','all_product_trading_volume_annual','USD',34000000000000,
   'Binance''s year-end report states $34T of 2025 all-product volume and 300M users. The record is a large active CEX control, while its broad metric is deliberately kept separate from spot-only measures.',
   'The outcome label is not a regulatory or solvency verdict. Token, custody, jurisdiction, and proof-of-reserves evidence require continued refresh rather than extrapolation from reported volume.',
   '{"operational_model":"Custodial multi-product centralized exchange offering spot, derivatives, and associated services through jurisdiction-specific entities.","chains":[],"token":{"launched":true,"symbol":"BNB","launch_date":"2017","role":"Exchange-ecosystem utility asset; token existence does not prove that the token caused venue success.","source_url":"https://academy.binance.com/en/articles/what-is-bnb"},"metrics":{"all_product_trading_volume_annual_usd":34000000000000,"users_reported":300000000,"period_end":"2025-12-31","source_url":"https://www.prnewswire.com/in/news-releases/binances-2025-end-of-year-report-trust-liquidity-and-web3-discovery-302657209.html","method_note":"Issuer-reported all-product volume. It cannot be added to spot-only, perpetual-only, or other venue metrics."},"success_factors":["global_liquidity_distribution","broad_product_suite","brand_and_user_distribution","exchange_ecosystem_token"],"risks":["jurisdictional_regulatory_risk","custody_and_counterparty_risk","issuer_reported_metric_scope","bnb_token_value_capture_uncertainty"],"synthesis":"Binance supplies the large-scale centralized-exchange control. It is useful for testing whether distribution and liquidity coincide with survival, but its reported all-product volume is not a like-for-like ranking input against other metric classes."}',
   '[{"title":"Binance 2025 end-of-year report","url":"https://www.prnewswire.com/in/news-releases/binances-2025-end-of-year-report-trust-liquidity-and-web3-discovery-302657209.html"},{"title":"Binance Academy: What is BNB?","url":"https://academy.binance.com/en/articles/what-is-bnb"},{"title":"Binance proof of reserves portal","url":"https://www.binance.com/en/proof-of-reserves"}]','2026-07-29'),
  ('bybit','cex','exchange','Bybit','2018',NULL,'successful_established','2024 reported average daily trading volume','reported_average_daily_trading_volume','USD',36000000000,
   'Bybit''s official 2025 vision announcement reports $36B average daily volume in 2024 and 60M users. A later proof-of-reserves update supplies a separate recovery/custody checkpoint; neither source turns platform volume into a solvency conclusion.',
   'This is an active-control classification with a major incident/recovery context. Recheck reserve attestations, legal availability, and independent liquidity metrics before treating current status as durable.',
   '{"operational_model":"Custodial centralized multi-product exchange with spot and derivatives services through exchange-managed accounts and order books.","chains":[],"token":{"launched":false,"symbol":null,"role":"No venue token is asserted from the reviewed Bybit sources; payment or ecosystem assets are not silently classified as an exchange token."},"metrics":{"reported_average_daily_trading_volume_usd":36000000000,"users_reported":60000000,"period_end":"2024-12-31","source_url":"https://www.bybit.com/en/press/post/bybit-unveils-2025-vision-a-user-centric-approach-to-crypto-innovation-blt02b02bc45c5a067d","method_note":"Issuer-reported average daily volume for 2024; not directly comparable to annual totals or third-party spot-only volume."},"success_factors":["derivatives_and_spot_product_suite","global_user_distribution","liquidity_and_execution_focus"],"risks":["custody_and_counterparty_risk","post_incident_recovery_risk","regulatory_change","issuer_reported_metric_scope"],"synthesis":"Bybit is deliberately a success-with-stress control: reported scale establishes material activity, while the separate reserve update makes incident recovery and customer-asset backing a visible hypothesis to monitor rather than an implied guarantee."}',
   '[{"title":"Bybit 2025 vision announcement","url":"https://www.bybit.com/en/press/post/bybit-unveils-2025-vision-a-user-centric-approach-to-crypto-innovation-blt02b02bc45c5a067d"},{"title":"Bybit proof-of-reserves recovery update","url":"https://www.bybit.com/en/press/post/fully-backed-within-72-hours-bybit-maintains-1-1-customer-assets-ratio-in-latest-proof-of-reserves-audited-report-by-hacken-bltb767a9461133831f"}]','2026-07-29'),
  ('bitstamp','cex','exchange','Bitstamp by Robinhood','2011',NULL,'successful_established','TTM net revenue at acquisition close','net_revenue_ttm','USD',95000000,
   'Robinhood''s acquisition-close release records that Bitstamp remained operating, held over 50 active licenses and registrations, served retail and institutional funded customers, and generated about $95M of TTM net revenue as of April 30, 2025.',
   'Acquisition is not a shutdown. The next evidence pass should measure post-acquisition operations, jurisdiction-by-jurisdiction licences, and independently comparable trading activity.',
   '{"operational_model":"Custodial centralized spot exchange and institutional venue operating as a Robinhood subsidiary after the 2025 acquisition.","chains":[],"token":{"launched":false,"symbol":null,"role":"No exchange token is asserted from the reviewed acquisition-close disclosure."},"metrics":{"net_revenue_ttm_usd":95000000,"funded_retail_customers":500000,"funded_institutional_customers":5000,"active_licenses_and_registrations_min":50,"period_end":"2025-04-30","source_url":"https://investors.robinhood.com/static-files/4183f04d-6658-438d-9045-64ffa8e7402d","method_note":"Acquirer-reported TTM net revenue as of April 30, 2025; it is not a trading-volume metric."},"success_factors":["long_operating_history","institutional_customer_base","licensed_jurisdictional_footprint","strategic_acquisition"],"risks":["post_acquisition_integration","custody_and_counterparty_risk","regulatory_change","metric_not_trading_volume"],"synthesis":"Bitstamp is a continuity and acquisition control. The cited release supports active operation and an institutional footprint at close, while avoiding the false conclusion that acquisition alone proves future success."}',
   '[{"title":"Robinhood closes Bitstamp acquisition","url":"https://investors.robinhood.com/static-files/4183f04d-6658-438d-9045-64ffa8e7402d"}]','2026-07-29');

INSERT OR REPLACE INTO exchange_case_features
  (kind, slug, lifecycle, operating_model, product_cohort, custody_model, primary_chain,
   chains, token_status, token_symbol, token_launch_date, token_launch_timing,
   token_strategy, token_source_url, metric_type, metric_unit, metric_window,
   metric_as_of, metric_observed_at, comparability_key, evidence, quality_label,
   quality_issues, lifecycle_evidence_date, last_verified_at, next_review_at,
   freshness_status, updated_at)
VALUES
  ('cex','coinbase','successful','Custodial multi-product exchange, brokerage, institutional platform, and infrastructure provider.','centralized_multi_product_exchange','custodial',NULL,'[]','not_identified',NULL,NULL,'unknown','no_venue_token_identified',NULL,'platform_trading_volume_annual','usd','calendar_2025','2025-12-31','2026-02-12','cex|centralized_multi_product_exchange|platform_trading_volume_annual|usd|calendar_2025','{"operating_model_source_indexes":[0],"custody_model_source_indexes":[0],"product_cohort_source_indexes":[0],"metric_source_indexes":[0],"lifecycle_source_indexes":[0],"token_source_indexes":[],"metric_observation_note":"SEC-filed annual company metric; source-specific definition retained."}','partial','["metric_not_spot_only","no_venue_token_claim"]','2026-02-12','2026-07-29','2026-08-05','current','2026-07-29'),
  ('cex','kraken','successful','Custodial centralized exchange and financial-services platform serving retail and institutional customers.','centralized_multi_product_exchange','custodial',NULL,'[]','not_identified',NULL,NULL,'unknown','no_venue_token_identified',NULL,'platform_transaction_volume_annual','usd','calendar_2025','2025-12-31','2026-01-01','cex|centralized_multi_product_exchange|platform_transaction_volume_annual|usd|calendar_2025','{"operating_model_source_indexes":[0],"custody_model_source_indexes":[0],"product_cohort_source_indexes":[0],"metric_source_indexes":[0],"lifecycle_source_indexes":[0],"token_source_indexes":[],"metric_observation_note":"Issuer-reported platform metric; retained apart from spot-only volume."}','partial','["metric_not_spot_only","no_venue_token_claim"]','2026-01-01','2026-07-29','2026-08-05','current','2026-07-29'),
  ('cex','binance','successful','Custodial multi-product centralized exchange offering spot, derivatives, and associated services through jurisdiction-specific entities.','centralized_multi_product_exchange','custodial',NULL,'[]','launched','BNB','2017','at_or_near_launch','exchange_ecosystem_utility','https://academy.binance.com/en/articles/what-is-bnb','all_product_trading_volume_annual','usd','calendar_2025','2025-12-31','2026-01-01','cex|centralized_multi_product_exchange|all_product_trading_volume_annual|usd|calendar_2025','{"operating_model_source_indexes":[0],"custody_model_source_indexes":[0],"product_cohort_source_indexes":[0],"metric_source_indexes":[0],"lifecycle_source_indexes":[0],"token_source_indexes":[1],"token_evidence_as_of":"2026-07-29","metric_observation_note":"Issuer-reported all-product volume; it is not a spot-only metric."}','verified','["metric_not_spot_only","jurisdiction_specific_operations"]','2026-01-01','2026-07-29','2026-08-05','current','2026-07-29'),
  ('cex','bybit','successful','Custodial centralized multi-product exchange with spot and derivatives services through exchange-managed accounts and order books.','centralized_multi_product_exchange','custodial',NULL,'[]','not_identified',NULL,NULL,'unknown','no_venue_token_identified',NULL,'reported_average_daily_trading_volume','usd','average_day_2024','2024-12-31','2025-01-01','cex|centralized_multi_product_exchange|reported_average_daily_trading_volume|usd|average_day_2024','{"operating_model_source_indexes":[0],"custody_model_source_indexes":[0],"product_cohort_source_indexes":[0],"metric_source_indexes":[0],"lifecycle_source_indexes":[0,1],"token_source_indexes":[],"metric_observation_note":"Issuer-reported 2024 average daily volume; incident/recovery source is distinct evidence."}','partial','["metric_not_spot_only","historical_metric_not_live","historical_lifecycle_evidence","no_venue_token_claim"]','2025-01-01','2026-07-29','2026-08-05','review_due','2026-07-29'),
  ('cex','bitstamp','successful','Custodial centralized spot exchange and institutional venue operating as a Robinhood subsidiary after the 2025 acquisition.','centralized_spot_exchange','custodial',NULL,'[]','not_identified',NULL,NULL,'unknown','no_venue_token_identified',NULL,'net_revenue_ttm','usd','ttm_ending_2025-04-30','2025-04-30','2025-06-02','cex|centralized_spot_exchange|net_revenue_ttm|usd|ttm_ending_2025-04-30','{"operating_model_source_indexes":[0],"custody_model_source_indexes":[0],"product_cohort_source_indexes":[0],"metric_source_indexes":[0],"lifecycle_source_indexes":[0],"token_source_indexes":[],"metric_observation_note":"Acquirer-reported TTM net revenue; not a trading-volume metric."}','partial','["metric_not_trading_volume","historical_metric_not_live","historical_lifecycle_evidence","no_venue_token_claim"]','2025-06-02','2026-07-29','2026-08-05','review_due','2026-07-29');
