-- Canonical RWA control profiles for BUIDL and Ondo OUSG.
-- Migration 0070 is reserved by the exchange-profile wave.

DROP TABLE IF EXISTS _rwa_control_profiles;
CREATE TABLE _rwa_control_profiles (
  slug TEXT PRIMARY KEY,
  profile TEXT NOT NULL,
  sources TEXT NOT NULL
);

INSERT INTO _rwa_control_profiles (slug, profile, sources) VALUES
('blackrock-buidl',
'{
  "type":"Restricted tokenized private-fund interest providing qualified investors exposure to cash, United States Treasury bills and repurchase agreements.",
  "legal_structure":{"issuer":"BlackRock USD Institutional Digital Liquidity Fund Ltd.","domicile":"British Virgin Islands","security":"Pooled investment fund interests represented by digital asset security tokens","offering":"Rule 506(c) private placement","investment_company_act":"Section 3(c)(7) exclusion"},
  "access":{"eligible_investors":"Qualified purchasers accepted through Securitize onboarding","transferability":"Only among pre-approved or whitelisted participants","initial_minimum_usd":5000000,"redemption_minimum_usd":250000,"minimum_note":"The launch release establishes the 5 million dollar initial minimum; the current redemption minimum is an RWA.xyz product-data observation and should be checked against live offering documents."},
  "current_observation":{"observed_at":"2026-08-03T16:48:03Z","source":"rwa-buidl","product_total_asset_value_usd":2673461059.240449,"net_asset_value_usd":1,"holder_addresses":113,"observed_seven_day_apy_pct":1.4705439273203145,"management_fee_range_pct":"0.20-0.50","network_names":["Aptos","Arbitrum","Avalanche C-Chain","BNB Chain","Ethereum","Optimism","Polygon","Solana","Tempo"],"native_token_rows":10,"bridge_token_rows":0},
  "economics":{"portfolio":"Cash, United States Treasury bills and repurchase agreements","income_distribution":"Daily accrued dividends are distributed monthly as new tokens","target_nav_usd":1,"target_nav_not_guaranteed":true,"holder_right":"A BUIDL token represents a restricted fund interest, not equity in BlackRock or Securitize."},
  "data_scope_notes":["Product total asset value is kept separate from Securitize platform AUM and assets under administration.","RWA.xyz labels ten current token rows native while seven rows use Wormhole NTT as a base protocol; contract-level provenance remains a review item rather than a claim that all representations are permissionless bridge tokens.","Seven-day APY is a dated trailing observation, not a promised return."],
  "canonical_profile":{
    "schema":"chaindump-entity-profile-source",
    "version":1,
    "classification":{"subtype":"rwa-treasuries","tags":["tokenized-fund","private-placement","qualified-purchaser","cash-management"],"chains":["Aptos","Arbitrum","Avalanche C-Chain","BNB Chain","Ethereum","Optimism","Polygon","Solana","Tempo"],"jurisdictions":["British Virgin Islands","United States"]},
    "status":{"operating_state":"operating","as_of":"2026-08-03","claim_ids":["claim:buidl:operating-state"]},
    "outcome":{"label":null,"as_of":null,"rule_id":null,"confidence":null,"claim_ids":[]},
    "sections":{
      "what_it_is":"BUIDL is a private pooled investment fund issued by a British Virgin Islands company and managed by BlackRock Financial Management. Its shares are represented as digital asset security tokens. The reviewed Form D claims Rule 506(c) and the Investment Company Act section 3(c)(7) exclusion; tokenization does not make the fund interest permissionless or exchange-listed.",
      "what_happened":"The fund launched on Ethereum in March 2024, added issuer-sponsored share classes across more public networks, and later entered controlled collateral and secondary-liquidity workflows. RWA.xyz recorded ten native token rows on nine named networks on 2026-08-03. Its product-level total asset value is stored as a dated metric, not repeated as an evergreen superlative.",
      "why_this_outcome":"BUIDL combines a familiar short-duration reserve portfolio with blockchain settlement, a regulated transfer-agent workflow and a large service-provider network. That combination plausibly reduced operational friction for already-qualified institutions. It does not show that public-chain deployment removed legal eligibility, wallet approval or transfer controls.",
      "strategic_choices":"The product targets a one-dollar share value, distributes accrued income as additional tokens, gates investors and wallets through Securitize, and expands through separate network share classes and selected collateral venues. Those choices favor controlled institutional distribution and composability over unrestricted bearer-style transfer.",
      "operating_model":"The fund invests all assets in cash, United States Treasury bills and repurchase agreements. BlackRock Financial Management manages investments; BNY Mellon provides custody and administration; Securitize provides the platform, transfer-agent, registrar and paying-agent functions; Securitize Markets acts as placement agent. Onboarding includes identity, sanctions and wallet checks, and peer transfers are limited to approved participants.",
      "token_and_value_capture":"BUIDL seeks a stable one-dollar token value while daily accrued dividends are paid monthly as new tokens. The current fee range varies by share class. Holders receive economics of the fund interest after expenses; the token does not establish a claim on BlackRock or Securitize equity, and a trailing APY observation is not a guaranteed return.",
      "counterfactual":"Without whitelisted transfer-agent controls, BUIDL could move more freely but would not preserve the documented private-placement workflow. Without multiple network share classes and collateral integrations, operations would be simpler but distribution and utility would be narrower. These are analytical trade-offs, not measured causal effects.",
      "risks_and_unknowns":"The launch disclosures warn that BUIDL may not maintain one dollar and that investors can lose principal. Material risks include private-placement illiquidity, eligibility and transfer restrictions, interest-rate and portfolio risk, issuer and service-provider dependence, smart-contract and wallet risk, and cross-network reconciliation. Public network visibility does not remove those constraints.",
      "lifecycle":"BUIDL launched on Ethereum on 2024-03-20. New share classes brought it to seven networks by 2025-03-25 and BNB Chain on 2025-11-14. A 2026 UniswapX workflow added bilateral onchain quote and settlement technology while retaining pre-qualification and whitelisting. The fund remained operating on 2026-08-03.",
      "outlook_and_watch":"Watch product-level asset value, share-class fees and dividends; changes to offering and eligibility terms; custody and transfer-agent arrangements; collateral integrations; and reconciliation of every network contract and Wormhole-enabled share class. Platform-wide Securitize figures must remain separate from BUIDL fund value, and current yield must remain a dated observation."
    },
    "section_dates":{"what_it_is":"2026-08-03","what_happened":"2026-08-03","why_this_outcome":"2026-08-03","strategic_choices":"2026-08-03","operating_model":"2026-08-03","token_and_value_capture":"2026-08-03","counterfactual":"2026-08-03","risks_and_unknowns":"2026-08-03","lifecycle":"2026-08-03","outlook_and_watch":"2026-08-03"},
    "section_claim_ids":{
      "what_it_is":["claim:buidl:legal-structure","claim:buidl:access"],
      "what_happened":["claim:buidl:launch","claim:buidl:chains","claim:buidl:current-market","claim:buidl:uniswap"],
      "why_this_outcome":["claim:buidl:why"],
      "strategic_choices":["claim:buidl:strategy"],
      "operating_model":["claim:buidl:assets","claim:buidl:access","claim:buidl:service-roles"],
      "token_and_value_capture":["claim:buidl:distribution","claim:buidl:value-capture"],
      "counterfactual":["claim:buidl:counterfactual"],
      "risks_and_unknowns":["claim:buidl:risks","claim:buidl:chains"],
      "lifecycle":["claim:buidl:launch","claim:buidl:solana","claim:buidl:bnb","claim:buidl:uniswap","claim:buidl:operating-state"],
      "outlook_and_watch":["claim:buidl:current-market","claim:buidl:risks","claim:buidl:chains"]
    },
    "metrics":[
      {"id":"metric:buidl:aum:2026-08-03","dimension":"aum","label":"BUIDL product total asset value","value":2673461059.240449,"unit":"usd","currency":"USD","window":{"start":null,"end":"2026-08-03T16:48:03Z","definition":"point_in_time"},"as_of":"2026-08-03T16:48:03Z","method":"aggregator_product_observation","scope":{"product":"BUIDL","operator":"Securitize","excludes":"Securitize platform AUM and assets under administration"},"formula":null,"raw_input_ids":[],"claim_ids":["claim:buidl:metric-aum"],"quality_flags":["product-only","aggregator-observation"]},
      {"id":"metric:buidl:yield-7d:2026-08-03","dimension":"yield","label":"Observed seven-day annualized percentage yield","value":1.4705439273203145,"unit":"percent","currency":null,"window":{"start":"2026-07-28","end":"2026-08-03","definition":"trailing_7_day_annualized_observation"},"as_of":"2026-08-03T16:48:03Z","method":"aggregator_product_observation","scope":{"product":"BUIDL"},"formula":null,"raw_input_ids":[],"claim_ids":["claim:buidl:metric-yield"],"quality_flags":["observed-not-promised","past-performance"]},
      {"id":"metric:buidl:holders:2026-08-03","dimension":"holders","label":"Holder addresses","value":113,"unit":"addresses","currency":null,"window":{"start":null,"end":"2026-08-03T16:48:03Z","definition":"point_in_time"},"as_of":"2026-08-03T16:48:03Z","method":"aggregator_address_observation","scope":{"product":"BUIDL","networks":"aggregator-supported token rows"},"formula":null,"raw_input_ids":[],"claim_ids":["claim:buidl:metric-holders"],"quality_flags":["addresses-not-investors"]}
    ],
    "events":[
      {"id":"event:buidl:launch:2024-03-20","type":"product_launch","date":"2024-03-20","date_precision":"day","amount_usd":null,"description":"BlackRock and Securitize launched BUIDL on Ethereum with a five-million-dollar initial minimum.","claim_ids":["claim:buidl:launch"]},
      {"id":"event:buidl:solana-share-class:2025-03-25","type":"network_expansion","date":"2025-03-25","date_precision":"day","amount_usd":null,"description":"A Solana share class expanded BUIDL to seven issuer-announced networks.","claim_ids":["claim:buidl:solana"]},
      {"id":"event:buidl:bnb-share-class:2025-11-14","type":"network_expansion","date":"2025-11-14","date_precision":"day","amount_usd":null,"description":"BUIDL launched a BNB Chain share class and became eligible for a Binance collateral workflow.","claim_ids":["claim:buidl:bnb"]},
      {"id":"event:buidl:uniswapx:2026-02-11","type":"distribution_integration","date":"2026-02-11","date_precision":"day","amount_usd":null,"description":"Securitize added a UniswapX RFQ workflow for pre-qualified and whitelisted BUIDL participants.","claim_ids":["claim:buidl:uniswap"]}
    ],
    "claims":[
      {"id":"claim:buidl:legal-structure","field_path":"analysis.sections.what_it_is.body","statement":"BUIDL is a BVI pooled investment fund interest offered under Rule 506(c) and relying on section 3(c)(7).","source_ids":["sec-buidl-form-d","sec-buidl-transfer-agent"],"evidence_locator":"Form D issuer, security and exemptions; transfer-agent agreement Exhibit A","support_direction":"supports","note":"The SEC warns that Form D information is issuer-reported and not Commission-verified.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:launch","field_path":"events[event:buidl:launch:2024-03-20]","statement":"BUIDL launched on Ethereum on 2024-03-20 with a five-million-dollar initial investment minimum.","source_ids":["securitize-buidl-launch","sec-buidl-form-d"],"evidence_locator":"Launch announcement and 2024 Form D","support_direction":"supports","note":null,"review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:assets","field_path":"analysis.sections.operating_model.body","statement":"The fund invests all total assets in cash, United States Treasury bills and repurchase agreements.","source_ids":["securitize-buidl-launch"],"evidence_locator":"Launch announcement portfolio description","support_direction":"supports","note":"This describes eligible portfolio composition, not a same-day audited holdings schedule.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:distribution","field_path":"analysis.sections.token_and_value_capture.body","statement":"BUIDL seeks a one-dollar value and distributes daily accrued dividends monthly as new tokens.","source_ids":["securitize-buidl-launch"],"evidence_locator":"Launch announcement product mechanics and disclosures","support_direction":"supports","note":"The same source says the fund may not maintain one dollar and past performance is not indicative of future results.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:access","field_path":"analysis.sections.operating_model.body","statement":"Securitize performs investor and wallet compliance checks and transfers are limited to approved participants.","source_ids":["sec-buidl-transfer-agent","securitize-buidl-launch"],"evidence_locator":"Agreement KYC, sanctions, wallet-monitoring and transfer provisions; launch transfer language","support_direction":"supports","note":"Public-chain settlement does not make BUIDL a permissionless token.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:service-roles","field_path":"analysis.sections.operating_model.body","statement":"BlackRock manages investments, BNY Mellon provides custody and administration, and Securitize performs platform and transfer-agent functions.","source_ids":["securitize-buidl-launch","sec-buidl-transfer-agent"],"evidence_locator":"Launch service-provider paragraph and transfer-agent agreement","support_direction":"supports","note":null,"review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:chains","field_path":"analysis.sections.what_happened.body","statement":"RWA.xyz observed ten native BUIDL token rows across nine named networks on 2026-08-03.","source_ids":["rwa-buidl"],"evidence_locator":"Current asset network_names, native_token_count, bridge_token_count and token rows","support_direction":"supports","note":"Seven rows name Wormhole NTT as a base protocol; native-versus-bridged provenance should be reviewed contract by contract.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:current-market","field_path":"analysis.sections.what_happened.body","statement":"RWA.xyz recorded material BUIDL product value, a one-dollar NAV and current holder and yield observations on 2026-08-03.","source_ids":["rwa-buidl"],"evidence_locator":"Server-rendered asset aggregates and update timestamp","support_direction":"supports","note":"Product observations are not Securitize platform AUM and yield is not promised.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:why","field_path":"analysis.sections.why_this_outcome.body","statement":"BUIDL adoption is plausibly supported by short-duration assets, controlled onchain settlement and institutional service providers.","source_ids":["securitize-buidl-launch","sec-buidl-transfer-agent","rwa-buidl"],"evidence_locator":"Product design, operating agreement and current product observation","support_direction":"context_only","note":"Analytical inference; the sources do not isolate causal contribution.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:strategy","field_path":"analysis.sections.strategic_choices.body","statement":"BUIDL combines a target one-dollar share, monthly token dividends, gated transfers, multi-network share classes and selected collateral integrations.","source_ids":["securitize-buidl-launch","sec-buidl-transfer-agent","securitize-buidl-solana","securitize-buidl-bnb"],"evidence_locator":"Product mechanics, transfer controls and network announcements","support_direction":"supports","note":null,"review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:value-capture","field_path":"analysis.sections.token_and_value_capture.body","statement":"BUIDL holders receive fund-interest economics after expenses, not equity or governance rights in BlackRock or Securitize.","source_ids":["sec-buidl-form-d","securitize-buidl-launch","rwa-buidl"],"evidence_locator":"Form D security type, launch mechanics and current share-class fee range","support_direction":"supports","note":"No platform-token value accrual is inferred.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:counterfactual","field_path":"analysis.sections.counterfactual.body","statement":"Removing transfer controls or multi-network distribution would change BUIDL access, compliance and operational trade-offs.","source_ids":["sec-buidl-transfer-agent","securitize-buidl-solana"],"evidence_locator":"Current transfer controls and network design","support_direction":"context_only","note":"Unquantified analytical counterfactual.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:risks","field_path":"analysis.sections.risks_and_unknowns.body","statement":"BUIDL carries principal-loss, private-placement, transfer, portfolio, service-provider, wallet and network risks.","source_ids":["securitize-buidl-launch","sec-buidl-transfer-agent","rwa-buidl"],"evidence_locator":"Launch disclosures, operating controls and current multi-network observation","support_direction":"supports","note":null,"review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:operating-state","field_path":"status.operating_state","statement":"BUIDL remained operating with material product value on 2026-08-03.","source_ids":["rwa-buidl"],"evidence_locator":"Current asset aggregates and token rows","support_direction":"supports","note":null,"review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:solana","field_path":"events[event:buidl:solana-share-class:2025-03-25]","statement":"A Solana share class launched on 2025-03-25, bringing BUIDL to seven announced networks at that date.","source_ids":["securitize-buidl-solana"],"evidence_locator":"Dated Solana launch announcement","support_direction":"supports","note":null,"review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:bnb","field_path":"events[event:buidl:bnb-share-class:2025-11-14]","statement":"BUIDL launched on BNB Chain and entered a Binance collateral workflow on 2025-11-14.","source_ids":["securitize-buidl-bnb"],"evidence_locator":"Dated BNB Chain and Binance announcement","support_direction":"supports","note":"Collateral eligibility does not make the shares freely transferable.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:uniswap","field_path":"events[event:buidl:uniswapx:2026-02-11]","statement":"A UniswapX RFQ workflow launched for pre-qualified and whitelisted BUIDL participants on 2026-02-11.","source_ids":["securitize-buidl-uniswap"],"evidence_locator":"Integration announcement participant and settlement description","support_direction":"supports","note":"The workflow is bilateral and controlled, not permissionless pool trading.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:metric-aum","field_path":"metrics[metric:buidl:aum:2026-08-03].value","statement":"RWA.xyz recorded 2673461059.240449 dollars of BUIDL product total asset value at retrieval.","source_ids":["rwa-buidl"],"evidence_locator":"Asset aggregate Total Asset Value","support_direction":"supports","note":"Product-only; excludes Securitize platform AUM and AUA.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:metric-yield","field_path":"metrics[metric:buidl:yield-7d:2026-08-03].value","statement":"RWA.xyz displayed a 1.4705439273203145 percent seven-day APY observation for BUIDL at retrieval.","source_ids":["rwa-buidl"],"evidence_locator":"Asset aggregate 7D APY","support_direction":"supports","note":"Trailing observation, not a promised return.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:buidl:metric-holders","field_path":"metrics[metric:buidl:holders:2026-08-03].value","statement":"RWA.xyz recorded 113 BUIDL holder addresses at retrieval.","source_ids":["rwa-buidl"],"evidence_locator":"Asset aggregate Holders","support_direction":"supports","note":"Addresses are not necessarily unique beneficial investors.","review":{"state":"pending","reviewer":null,"reviewed_at":null}}
    ],
    "freshness":{"state":"current","last_reviewed_at":"2026-08-03","next_review_at":"2026-08-10","field_reviews":[]},
    "confidence":"medium",
    "extensions":{
      "methodology_notes":["freshness.last_reviewed_at records evidence assembly and source verification, not human approval; every claim remains pending until an editor reviews it.","BUIDL product value is not Securitize platform AUM or assets under administration.","Observed APY is not a promised return, and public-chain shares remain subject to private-fund eligibility and whitelist controls."],
      "structured_analysis":{"strategic_choices":[{"decision":"Represent restricted fund shares on public networks while retaining transfer-agent controls.","consequence":"Qualified investors gain blockchain settlement and wallet custody while access and transfers remain permissioned.","claim_ids":["claim:buidl:access","claim:buidl:strategy"]},{"decision":"Expand through network share classes and controlled collateral integrations.","consequence":"Distribution and utility broaden, while contract, interoperability and venue dependencies increase.","claim_ids":["claim:buidl:chains","claim:buidl:bnb","claim:buidl:uniswap"]},{"decision":"Target one dollar and distribute income as new tokens.","consequence":"The share can function as an onchain cash-management instrument, but one-dollar stability and future yield are not guaranteed.","claim_ids":["claim:buidl:distribution","claim:buidl:risks"]}],"unknowns":[{"question":"What are the current offering terms and management fee for every BUIDL share class?","resolution_trigger":"Current issuer-approved offering documents and fee schedule for each class."},{"question":"How should every current token row be classified as native, interoperable or bridged?","resolution_trigger":"Issuer-signed contract inventory reconciled to supply on every network."},{"question":"How do current audited fund holdings, liabilities and expenses reconcile to onchain token value?","resolution_trigger":"Current audited financial statements plus class-level supply reconciliation."}]},
      "review_metadata":{"schema":"forensic-freshness-v1","status_basis":"direct_current","status_as_of":"2026-08-03","last_verified_at":"2026-08-03","next_review_at":"2026-08-10","stale":false}
    }
  }
}',
'[
  {"id":"sec-buidl-form-d","title":"BlackRock USD Institutional Digital Liquidity Fund Ltd. Form D","publisher":"U.S. Securities and Exchange Commission","url":"https://www.sec.gov/Archives/edgar/data/2013810/000201439024000001/xslFormDX01/primary_doc.xml","source_role":"primary","tier":"A","role":"primary","accessed_at":"2026-08-03","source_date":"2024-03-18","source_date_kind":"published","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"mechanism","stale_after":"2026-08-10","stale":false},
  {"id":"sec-buidl-transfer-agent","title":"Platform Services, Transfer Agent and Registrar Agreement","publisher":"BlackRock USD Institutional Digital Liquidity Fund Ltd. and Securitize LLC","url":"https://www.sec.gov/Archives/edgar/data/2094496/000121390026042685/ea026411904ex10-9.htm","source_role":"primary","tier":"A","role":"primary","accessed_at":"2026-08-03","source_date":"2024-03-14","source_date_kind":"event","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"mechanism","stale_after":"2026-08-10","stale":false},
  {"id":"securitize-buidl-launch","title":"BlackRock Launches Its First Tokenized Fund, BUIDL, on the Ethereum Network","publisher":"BlackRock and Securitize","url":"https://securitize.io/learn/press/blackrock-launches-first-tokenized-fund-buidl-on-the-ethereum-network","source_role":"primary","tier":"B","role":"primary","accessed_at":"2026-08-03","source_date":"2024-03-20","source_date_kind":"published","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"mechanism","stale_after":"2026-08-10","stale":false},
  {"id":"securitize-buidl-solana","title":"BlackRock and Securitize Debut New BUIDL Share Class on Solana Network","publisher":"Securitize","url":"https://securitize.io/learn/press/blackRock-and-securitize-debut-new-buidl-share-class-on-solana-network","source_role":"primary","tier":"B","role":"primary","accessed_at":"2026-08-03","source_date":"2025-03-25","source_date_kind":"event","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"historical_event","stale_after":null,"stale":false},
  {"id":"securitize-buidl-bnb","title":"BUIDL Accepted as Binance Collateral and Launches on BNB Chain","publisher":"Securitize","url":"https://securitize.io/press/BlackRock-BUIDL-Tokenized-by-Securitize-Now-Accepted-on-Binance-and-Launches-on-BNB-Chain","source_role":"primary","tier":"B","role":"primary","accessed_at":"2026-08-03","source_date":"2025-11-14","source_date_kind":"event","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"historical_event","stale_after":null,"stale":false},
  {"id":"securitize-buidl-uniswap","title":"Uniswap Labs and Securitize Collaborate on BUIDL Liquidity Options","publisher":"Securitize","url":"https://securitize.io/press/Uniswap-Labs-and-Securitize-Collaborate-to-Unlock-Liquidity-Option-for-BlackRock-BUIDL","source_role":"primary","tier":"B","role":"primary","accessed_at":"2026-08-03","source_date":"2026-02-11","source_date_kind":"event","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"mechanism","stale_after":"2026-08-10","stale":false},
  {"id":"rwa-buidl","title":"BlackRock USD Institutional Digital Liquidity Fund asset profile","publisher":"RWA.xyz","url":"https://app.rwa.xyz/assets/BUIDL","source_role":"aggregator","tier":"C","role":"aggregator","accessed_at":"2026-08-03T16:48:03Z","source_date":"2026-08-03","source_date_kind":"observed","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"current_state","stale_after":"2026-08-10","stale":false}
]'),

('ondo-finance',
'{
  "type":"Ondo OUSG product profile: restricted tokenized limited-partnership interests providing qualified purchasers exposure to short-term United States government securities and cash-management funds.",
  "scope":"This profile covers OUSG, not the whole Ondo platform, USDY, Ondo Stocks or the ONDO governance token.",
  "legal_structure":{"issuer":"Ondo I LP","domicile":"Delaware, United States","security":"Pooled investment fund and limited partnership interests","offering":"Rule 506(c) private placement","investment_company_act":"Section 3(c)(7) exclusion"},
  "access":{"eligible_investors":"Onboarded qualified purchasers in eligible jurisdictions","transferability":"Only between already-onboarded Qualified Access Fund investors","instant_minimum_usd":5000,"non_instant_minimum_subscription_usd":100000,"non_instant_minimum_redemption_usd":50000},
  "current_observation":{"observed_at":"2026-08-03T16:48:03Z","official_product":{"reported_value_usd":378352807.35,"net_asset_value_usd":116.075451,"observed_apy_pct":3.43,"reported_chain_scope":["Ethereum","XRP Ledger"]},"aggregator_onchain":{"total_asset_value_usd":450853994.96748495,"net_asset_value_usd":116.075451,"holder_addresses":60,"observed_seven_day_apy_pct":3.287901415899392,"network_names":["Ethereum","Polygon","Solana","XRP Ledger"]}},
  "portfolio_observation":{"as_of":"2026-07-31T20:00:00Z","total_underlying_assets_usd":378352807.77000004,"average_seven_day_yield_pct":3.54,"average_thirty_day_yield_pct":3.43,"holdings_note":"The official page listed tokenized cash-management funds, USDC, bank deposits and other cash balances; composition is a dated snapshot."},
  "economics":{"income_treatment":"Underlying net income increases OUSG NAV rather than promising a fixed payout.","management_fee_pct":0.15,"management_fee_waived_until":"2027-01-01","fund_expense_cap_pct":0.15,"ondo_token_note":"No reviewed source establishes direct OUSG fee or income accrual to the separate ONDO governance token."},
  "data_scope_notes":["Official OUSG product reporting and RWA.xyz onchain total asset value use different scopes and are stored as separate, non-additive observations.","OUSG product value is not Ondo platform TVL.","Observed APY and portfolio yields are historical observations, not promised returns."],
  "canonical_profile":{
    "schema":"chaindump-entity-profile-source",
    "version":1,
    "classification":{"subtype":"rwa-treasuries","tags":["tokenized-fund","private-placement","qualified-purchaser","fund-of-funds","cash-management"],"chains":["Ethereum","Polygon","Solana","XRP Ledger"],"jurisdictions":["United States"]},
    "status":{"operating_state":"operating","as_of":"2026-08-03","claim_ids":["claim:ousg:operating-state"]},
    "outcome":{"label":null,"as_of":null,"rule_id":null,"confidence":null,"claim_ids":[]},
    "sections":{
      "what_it_is":"OUSG is the Ondo Short-Term US Government Treasuries Fund, issued by Ondo I LP as limited-partnership interests. The reviewed Form D identifies pooled investment fund interests offered under Rule 506(c) with a section 3(c)(7) exclusion. The token is therefore a restricted fund interest for qualified purchasers, not a permissionless Treasury token.",
      "what_happened":"OUSG began selling interests in February 2023, expanded from Ethereum to Polygon, Solana and XRP Ledger, and changed its portfolio from a single exchange-traded-fund wrapper toward several tokenized cash-management funds plus liquidity reserves. Current official product reporting and an independent onchain aggregator show different totals and scopes; both are stored separately rather than combined.",
      "why_this_outcome":"OUSG gives onboarded institutions one controlled interface to several underlying government-securities and cash-management vehicles, daily NAV accounting and around-the-clock stablecoin conversion paths. That design plausibly improves operational access and diversification, while adding another fund, adviser, custody, smart-contract and liquidity layer between an investor and the underlying assets.",
      "strategic_choices":"Ondo chose a multi-manager fund-of-funds portfolio, stablecoin and bank liquidity buffers, NAV appreciation for the accumulating OUSG share, qualified-purchaser gating, and native issuance on several networks. These choices favor controlled liquidity and portfolio flexibility rather than unrestricted transfer or a fixed promised yield.",
      "operating_model":"Ondo I LP holds underlying tokenized Treasury and money-market funds plus bank deposits and stablecoins. Ondo Capital Management advises the fund and Ondo Finance provides tokenization technology. Investors complete KYC and qualified-purchaser onboarding; subscriptions, redemptions, transfers and receipt are limited to approved participants. NAV is generally updated each business day, and instant routes remain subject to limits and service availability.",
      "token_and_value_capture":"Net income from underlying holdings raises OUSG NAV; OUSG does not promise a fixed return. The official product page states a 0.15 percent management fee waived through 2027-01-01 and fund expenses capped at 0.15 percent. Those economics belong to the OUSG fund and adviser relationship; no reviewed evidence supports direct value accrual from OUSG to the separate ONDO token.",
      "counterfactual":"Holding underlying funds or government securities directly could remove an Ondo layer but would forgo OUSG consolidation, tokenization and stablecoin conversion. A single-manager portfolio would be easier to explain but less diversified across service providers. Permissionless transfer would broaden access but conflict with the documented private-fund eligibility model.",
      "risks_and_unknowns":"Investors face possible total loss, private-placement and transfer restrictions, underlying-fund, interest-rate, liquidity, adviser, custody, stablecoin, smart-contract and network risk. Official product value and aggregator onchain value do not currently reconcile because their chain and reporting scopes differ. That gap must remain visible, and observed APY must not be presented as promised return.",
      "lifecycle":"The amended Form D records first sale on 2023-02-06. Ondo announced native Solana deployment in December 2023, Polygon marketplace access in February 2025 and live XRP Ledger issuance in June 2025. OUSG remained active on 2026-08-03 with current product reporting, a dated portfolio schedule and four aggregator-observed network representations.",
      "outlook_and_watch":"Watch reconciliation between official product reporting, underlying holdings and every network representation; changes to eligibility, minimums and instant-liquidity limits; the 2027 fee-waiver expiry; stablecoin and custody dependencies; portfolio diversification; and any evidence connecting OUSG economics to other Ondo products or tokens. Keep OUSG AUM separate from Ondo platform TVL."
    },
    "section_dates":{"what_it_is":"2026-08-03","what_happened":"2026-08-03","why_this_outcome":"2026-08-03","strategic_choices":"2026-08-03","operating_model":"2026-08-03","token_and_value_capture":"2026-08-03","counterfactual":"2026-08-03","risks_and_unknowns":"2026-08-03","lifecycle":"2026-08-03","outlook_and_watch":"2026-08-03"},
    "section_claim_ids":{
      "what_it_is":["claim:ousg:legal-structure","claim:ousg:eligibility"],
      "what_happened":["claim:ousg:chains","claim:ousg:portfolio","claim:ousg:current-official","claim:ousg:current-market"],
      "why_this_outcome":["claim:ousg:why"],
      "strategic_choices":["claim:ousg:strategy"],
      "operating_model":["claim:ousg:portfolio","claim:ousg:eligibility","claim:ousg:transfer","claim:ousg:nav-mechanic"],
      "token_and_value_capture":["claim:ousg:nav-mechanic","claim:ousg:fees","claim:ousg:value-capture"],
      "counterfactual":["claim:ousg:counterfactual"],
      "risks_and_unknowns":["claim:ousg:risks","claim:ousg:current-official","claim:ousg:current-market"],
      "lifecycle":["claim:ousg:legal-structure","claim:ousg:solana","claim:ousg:polygon","claim:ousg:xrpl","claim:ousg:operating-state"],
      "outlook_and_watch":["claim:ousg:fees","claim:ousg:current-official","claim:ousg:current-market","claim:ousg:risks"]
    },
    "metrics":[
      {"id":"metric:ousg:aum-official:2026-08-03","dimension":"aum","label":"OUSG official reported product value","value":378352807.35,"unit":"usd","currency":"USD","window":{"start":null,"end":"2026-08-03T00:00:00Z","definition":"point_in_time"},"as_of":"2026-08-03T00:00:00Z","method":"issuer_product_observation","scope":{"product":"OUSG","reported_chains":["Ethereum","XRP Ledger"],"excludes":"Ondo platform TVL"},"formula":null,"raw_input_ids":[],"claim_ids":["claim:ousg:metric-aum"],"quality_flags":["product-only","official-scope-excludes-observed-Solana-and-Polygon-rows"]},
      {"id":"metric:ousg:outstanding-onchain:2026-08-03","dimension":"outstanding_value","label":"OUSG aggregator onchain total asset value","value":450853994.96748495,"unit":"usd","currency":"USD","window":{"start":null,"end":"2026-08-03T16:48:03Z","definition":"point_in_time"},"as_of":"2026-08-03T16:48:03Z","method":"aggregator_product_observation","scope":{"product":"OUSG","networks":["Ethereum","Polygon","Solana","XRP Ledger"],"excludes":"Ondo platform TVL"},"formula":null,"raw_input_ids":[],"claim_ids":["claim:ousg:metric-outstanding"],"quality_flags":["non-additive-with-official-aum","does-not-reconcile-to-official-chain-scope","aggregator-observation"]},
      {"id":"metric:ousg:yield:2026-08-03","dimension":"yield","label":"OUSG official observed APY","value":3.43,"unit":"percent","currency":null,"window":{"start":null,"end":"2026-08-03T00:00:00Z","definition":"issuer_reported_trailing_observation"},"as_of":"2026-08-03T00:00:00Z","method":"issuer_product_observation","scope":{"product":"OUSG"},"formula":null,"raw_input_ids":[],"claim_ids":["claim:ousg:metric-yield"],"quality_flags":["observed-not-promised","past-performance"]},
      {"id":"metric:ousg:holders:2026-08-03","dimension":"holders","label":"OUSG holder addresses","value":60,"unit":"addresses","currency":null,"window":{"start":null,"end":"2026-08-03T16:48:03Z","definition":"point_in_time"},"as_of":"2026-08-03T16:48:03Z","method":"aggregator_address_observation","scope":{"product":"OUSG","networks":"aggregator-supported token rows"},"formula":null,"raw_input_ids":[],"claim_ids":["claim:ousg:metric-holders"],"quality_flags":["addresses-not-investors"]}
    ],
    "events":[
      {"id":"event:ousg:first-sale:2023-02-06","type":"first_sale","date":"2023-02-06","date_precision":"day","amount_usd":null,"description":"The amended Form D records OUSG issuer Ondo I LP first selling interests on 2023-02-06.","claim_ids":["claim:ousg:legal-structure"]},
      {"id":"event:ousg:solana:2023-12-19","type":"network_expansion","date":"2023-12-19","date_precision":"day","amount_usd":null,"description":"Ondo announced native OUSG deployment on Solana.","claim_ids":["claim:ousg:solana"]},
      {"id":"event:ousg:polygon:2025-02-20","type":"distribution_integration","date":"2025-02-20","date_precision":"day","amount_usd":null,"description":"OUSG became available to qualifying investors through Assetera on Polygon.","claim_ids":["claim:ousg:polygon"]},
      {"id":"event:ousg:xrpl:2025-06-11","type":"network_expansion","date":"2025-06-11","date_precision":"day","amount_usd":null,"description":"Ondo launched OUSG on XRP Ledger with RLUSD subscription and redemption support for qualified purchasers.","claim_ids":["claim:ousg:xrpl"]}
    ],
    "claims":[
      {"id":"claim:ousg:legal-structure","field_path":"analysis.sections.what_it_is.body","statement":"Ondo I LP offers pooled investment fund and limited partnership interests under Rule 506(c) and section 3(c)(7); first sale was 2023-02-06.","source_ids":["sec-ousg-form-d","ondo-ousg-important"],"evidence_locator":"Form D issuer, securities, exemptions and first-sale fields; Ondo legal notes","support_direction":"supports","note":"Form D is issuer-reported and is not SEC approval or verification.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:eligibility","field_path":"analysis.sections.operating_model.body","statement":"OUSG is limited to onboarded qualified purchasers in eligible jurisdictions.","source_ids":["ondo-ousg-product","ondo-ousg-eligibility","ondo-ousg-important"],"evidence_locator":"Product eligibility card, onboarding criteria and legal notes","support_direction":"supports","note":null,"review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:transfer","field_path":"analysis.sections.operating_model.body","statement":"OUSG may be transferred or received only by already-onboarded Qualified Access Fund investors.","source_ids":["ondo-ousg-overview","ondo-ousg-eligibility"],"evidence_locator":"Overview transfer restrictions and eligibility page","support_direction":"supports","note":"OUSG is not a permissionless token even when represented on public chains.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:portfolio","field_path":"analysis.sections.operating_model.body","statement":"OUSG holds tokenized short-duration government and money-market funds plus bank and stablecoin liquidity.","source_ids":["ondo-ousg-product","ondo-ousg-overview"],"evidence_locator":"Current portfolio table and product overview","support_direction":"supports","note":"Holdings and weights are point-in-time and can change.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:nav-mechanic","field_path":"analysis.sections.token_and_value_capture.body","statement":"Underlying net income is reinvested and generally increases OUSG NAV, which is updated each business day.","source_ids":["ondo-ousg-yield","ondo-ousg-overview"],"evidence_locator":"Yield accrual, APY and NAV-update documentation","support_direction":"supports","note":"Observed APY is backward-looking and actual yield varies.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:fees","field_path":"analysis.sections.token_and_value_capture.body","statement":"The current OUSG page states a 0.15 percent management-fee cap waived until 2027-01-01 and a 0.15 percent fund-expense cap.","source_ids":["ondo-ousg-product"],"evidence_locator":"Current fees panel and tooltip","support_direction":"supports","note":"This current page supersedes older documentation with an earlier waiver date.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:chains","field_path":"analysis.sections.what_happened.body","statement":"RWA.xyz observed native OUSG token rows on Ethereum, Polygon, Solana and XRP Ledger on 2026-08-03.","source_ids":["rwa-ousg","ondo-ousg-solana","ondo-ousg-polygon","ondo-ousg-xrpl"],"evidence_locator":"Current network and token arrays plus dated issuer network announcements","support_direction":"supports","note":"Network representations remain subject to OUSG eligibility and whitelist controls.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:current-official","field_path":"analysis.sections.what_happened.body","statement":"Ondo reported 378352807.35 dollars of OUSG product value across Ethereum and XRP Ledger with a 116.075451 dollar NAV on 2026-08-03.","source_ids":["ondo-ousg-product"],"evidence_locator":"Server-rendered current assetData and history","support_direction":"supports","note":"The page scope excludes aggregator-observed Solana and Polygon rows and is not Ondo platform TVL.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:current-market","field_path":"analysis.sections.what_happened.body","statement":"RWA.xyz recorded 450853994.96748495 dollars across four OUSG network rows and 60 holder addresses at retrieval.","source_ids":["rwa-ousg"],"evidence_locator":"Server-rendered asset aggregates and token rows","support_direction":"supports","note":"This onchain total is non-additive with and does not currently reconcile to official product reporting.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:why","field_path":"analysis.sections.why_this_outcome.body","statement":"OUSG adoption is plausibly supported by consolidated multi-manager exposure, daily NAV and controlled stablecoin conversion.","source_ids":["ondo-ousg-overview","ondo-ousg-yield","ondo-ousg-product"],"evidence_locator":"Portfolio, mint-redemption and NAV mechanics","support_direction":"context_only","note":"Analytical inference; sources do not isolate causal contribution.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:strategy","field_path":"analysis.sections.strategic_choices.body","statement":"OUSG uses a multi-manager portfolio, liquidity buffers, NAV appreciation, qualified-purchaser gating and multiple native network representations.","source_ids":["ondo-ousg-product","ondo-ousg-overview","ondo-ousg-yield","rwa-ousg"],"evidence_locator":"Current holdings, product mechanics, eligibility and network rows","support_direction":"supports","note":null,"review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:value-capture","field_path":"analysis.sections.token_and_value_capture.body","statement":"OUSG holder economics come from fund NAV after expenses; reviewed sources do not establish direct OUSG economics accruing to ONDO.","source_ids":["ondo-ousg-yield","ondo-ousg-product","ondo-ousg-important"],"evidence_locator":"Yield mechanics, fee panel and legal operator relationships","support_direction":"supports","note":"The absence of a documented link is not proof that no commercial relationship exists outside reviewed sources.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:counterfactual","field_path":"analysis.sections.counterfactual.body","statement":"Direct underlying holdings, a single-manager portfolio or unrestricted transfers would change OUSG cost, diversification, access and compliance trade-offs.","source_ids":["ondo-ousg-product","ondo-ousg-overview","ondo-ousg-eligibility"],"evidence_locator":"Current portfolio, service and transfer design","support_direction":"context_only","note":"Unquantified analytical counterfactual.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:risks","field_path":"analysis.sections.risks_and_unknowns.body","statement":"OUSG carries possible total loss plus private-fund, underlying-asset, rate, liquidity, service-provider, stablecoin, contract and network risks.","source_ids":["ondo-ousg-important","ondo-ousg-overview","ondo-ousg-product","rwa-ousg"],"evidence_locator":"Legal risk notes, operating mechanics and current scope mismatch","support_direction":"supports","note":"Observed APY is not a guaranteed return.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:operating-state","field_path":"status.operating_state","statement":"OUSG remained operating with current product and onchain observations on 2026-08-03.","source_ids":["ondo-ousg-product","rwa-ousg"],"evidence_locator":"Current product assetData, portfolio and aggregator token rows","support_direction":"supports","note":null,"review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:solana","field_path":"events[event:ousg:solana:2023-12-19]","statement":"Ondo announced native OUSG deployment on Solana on 2023-12-19.","source_ids":["ondo-ousg-solana"],"evidence_locator":"Dated Solana expansion announcement","support_direction":"supports","note":null,"review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:polygon","field_path":"events[event:ousg:polygon:2025-02-20]","statement":"OUSG became available to qualifying Assetera investors on Polygon on 2025-02-20.","source_ids":["ondo-ousg-polygon"],"evidence_locator":"Dated Assetera and Polygon announcement","support_direction":"supports","note":"Marketplace access remained limited to qualifying investors.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:xrpl","field_path":"events[event:ousg:xrpl:2025-06-11]","statement":"OUSG launched on XRP Ledger with RLUSD mint and redemption support for qualified purchasers on 2025-06-11.","source_ids":["ondo-ousg-xrpl"],"evidence_locator":"Dated XRP Ledger launch announcement","support_direction":"supports","note":null,"review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:metric-aum","field_path":"metrics[metric:ousg:aum-official:2026-08-03].value","statement":"Ondo reported 378352807.35 dollars of OUSG value in its current Ethereum and XRP Ledger product view on 2026-08-03.","source_ids":["ondo-ousg-product"],"evidence_locator":"Current assetData tvlUsd total and chain fields","support_direction":"supports","note":"Product-only, not platform TVL; official chain scope differs from the aggregator.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:metric-outstanding","field_path":"metrics[metric:ousg:outstanding-onchain:2026-08-03].value","statement":"RWA.xyz recorded 450853994.96748495 dollars of OUSG total asset value across four network rows at retrieval.","source_ids":["rwa-ousg"],"evidence_locator":"Asset aggregate Total Asset Value and network token rows","support_direction":"supports","note":"Non-additive with official OUSG reporting and not Ondo platform TVL.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:metric-yield","field_path":"metrics[metric:ousg:yield:2026-08-03].value","statement":"Ondo displayed a 3.43 percent OUSG APY observation on 2026-08-03.","source_ids":["ondo-ousg-product","ondo-ousg-yield"],"evidence_locator":"Current assetData APY and APY methodology","support_direction":"supports","note":"Backward-looking observation, not a promised return.","review":{"state":"pending","reviewer":null,"reviewed_at":null}},
      {"id":"claim:ousg:metric-holders","field_path":"metrics[metric:ousg:holders:2026-08-03].value","statement":"RWA.xyz recorded 60 OUSG holder addresses at retrieval.","source_ids":["rwa-ousg"],"evidence_locator":"Asset aggregate Holders","support_direction":"supports","note":"Addresses are not necessarily unique beneficial investors.","review":{"state":"pending","reviewer":null,"reviewed_at":null}}
    ],
    "freshness":{"state":"current","last_reviewed_at":"2026-08-03","next_review_at":"2026-08-10","field_reviews":[]},
    "confidence":"medium",
    "extensions":{
      "methodology_notes":["freshness.last_reviewed_at records evidence assembly and source verification, not human approval; every claim remains pending until an editor reviews it.","Official OUSG product value and aggregator onchain value have different scopes and are non-additive.","OUSG observed yield is not a promised return; OUSG is a restricted fund interest rather than a permissionless token.","OUSG product AUM is not Ondo platform TVL, and no direct OUSG-to-ONDO value accrual is inferred."],
      "structured_analysis":{"strategic_choices":[{"decision":"Aggregate several tokenized cash-management funds inside OUSG.","consequence":"Investors receive a single tokenized fund interest with provider diversification while accepting another fee, adviser and custody layer.","claim_ids":["claim:ousg:portfolio","claim:ousg:strategy"]},{"decision":"Use NAV appreciation and controlled instant stablecoin routes.","consequence":"Income compounds into the share price and access can operate outside bank hours, subject to liquidity limits and service availability.","claim_ids":["claim:ousg:nav-mechanic","claim:ousg:strategy"]},{"decision":"Issue on several networks while retaining qualified-purchaser and whitelist controls.","consequence":"Distribution broadens without making the fund interest permissionless.","claim_ids":["claim:ousg:chains","claim:ousg:eligibility","claim:ousg:transfer"]}],"unknowns":[{"question":"Why does official OUSG reporting cover Ethereum and XRP Ledger while RWA.xyz also records Solana and Polygon value?","resolution_trigger":"Issuer contract-level supply and NAV reconciliation across every network."},{"question":"What fees apply after the current management-fee waiver expires?","resolution_trigger":"Current offering documents and an issuer fee notice at or before 2027-01-01."},{"question":"How do underlying-fund expenses, cash drag and liquidity-provider costs affect net OUSG yield?","resolution_trigger":"Current audited statements and a complete expense and liquidity-provider schedule."},{"question":"Does any OUSG revenue or governance authority accrue directly to ONDO?","resolution_trigger":"Binding issuer, adviser or DAO documentation showing the mechanism."}]},
      "review_metadata":{"schema":"forensic-freshness-v1","status_basis":"direct_current","status_as_of":"2026-08-03","last_verified_at":"2026-08-03","next_review_at":"2026-08-10","stale":false}
    }
  }
}',
'[
  {"id":"sec-ousg-form-d","title":"Ondo I LP Form D Amendment","publisher":"U.S. Securities and Exchange Commission","url":"https://www.sec.gov/Archives/edgar/data/1957431/000195743125000001/xslFormDX01/primary_doc.xml","source_role":"primary","tier":"A","role":"primary","accessed_at":"2026-08-03","source_date":"2025-01-21","source_date_kind":"published","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"mechanism","stale_after":"2026-08-10","stale":false},
  {"id":"ondo-ousg-product","title":"Ondo Short-Term US Treasuries Fund product page","publisher":"Ondo Finance","url":"https://ondo.finance/ousg","source_role":"primary","tier":"B","role":"primary","accessed_at":"2026-08-03T16:48:03Z","source_date":"2026-08-03","source_date_kind":"observed","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"current_state","stale_after":"2026-08-10","stale":false},
  {"id":"ondo-ousg-overview","title":"OUSG overview","publisher":"Ondo Finance","url":"https://docs.ondo.finance/qualified-access-products/ousg/overview","source_role":"primary","tier":"B","role":"primary","accessed_at":"2026-08-03","source_date":"2026-08-03","source_date_kind":"observed","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"mechanism","stale_after":"2026-08-10","stale":false},
  {"id":"ondo-ousg-yield","title":"OUSG yield mechanics","publisher":"Ondo Finance","url":"https://docs.ondo.finance/qualified-access-products/ousg/yield","source_role":"primary","tier":"B","role":"primary","accessed_at":"2026-08-03","source_date":"2026-08-03","source_date_kind":"observed","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"mechanism","stale_after":"2026-08-10","stale":false},
  {"id":"ondo-ousg-eligibility","title":"OUSG eligibility and onboarding","publisher":"Ondo Finance","url":"https://docs.ondo.finance/qualified-access-products/ousg/eligibility-and-onboarding","source_role":"primary","tier":"B","role":"primary","accessed_at":"2026-08-03","source_date":"2026-08-03","source_date_kind":"observed","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"mechanism","stale_after":"2026-08-10","stale":false},
  {"id":"ondo-ousg-important","title":"OUSG important legal notes","publisher":"Ondo Finance","url":"https://docs.ondo.finance/qualified-access-products/ousg/important-notes","source_role":"primary","tier":"A","role":"primary","accessed_at":"2026-08-03","source_date":"2026-08-03","source_date_kind":"observed","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"mechanism","stale_after":"2026-08-10","stale":false},
  {"id":"ondo-ousg-solana","title":"Ondo expansion to Solana","publisher":"Ondo Finance","url":"https://ondo.finance/blog/the-next-step-in-ondos-expansion-exploring-the-low-latency-frontier","source_role":"primary","tier":"B","role":"primary","accessed_at":"2026-08-03","source_date":"2023-12-19","source_date_kind":"event","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"historical_event","stale_after":null,"stale":false},
  {"id":"ondo-ousg-polygon","title":"OUSG available on Assetera and Polygon","publisher":"Ondo Finance","url":"https://ondo.finance/blog/ousg-is-now-available-on-assetera-expanding-access-to-tokenized-us-treasuries-in-europe","source_role":"primary","tier":"B","role":"primary","accessed_at":"2026-08-03","source_date":"2025-02-20","source_date_kind":"event","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"historical_event","stale_after":null,"stale":false},
  {"id":"ondo-ousg-xrpl","title":"OUSG launches on XRP Ledger","publisher":"Ondo Finance","url":"https://ondo.finance/blog/ondo-finance-brings-tokenized-treasuries-to-the-xrp-ledger-with-seamless-mint-redeem-via-ripples-rlusd-stablecoin","source_role":"primary","tier":"B","role":"primary","accessed_at":"2026-08-03","source_date":"2025-06-11","source_date_kind":"event","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"historical_event","stale_after":null,"stale":false},
  {"id":"rwa-ousg","title":"Ondo Short-Term US Government Bond Fund asset profile","publisher":"RWA.xyz","url":"https://app.rwa.xyz/assets/OUSG","source_role":"aggregator","tier":"C","role":"aggregator","accessed_at":"2026-08-03T16:48:03Z","source_date":"2026-08-03","source_date_kind":"observed","last_verified_at":"2026-08-03","checked_at":"2026-08-03","access_state":"reachable","evidence_scope":"current_state","stale_after":"2026-08-10","stale":false}
]');

UPDATE rwa_depin
SET
  name = CASE lower(slug)
    WHEN 'blackrock-buidl' THEN 'BlackRock BUIDL'
    WHEN 'ondo-finance' THEN 'Ondo Finance / OUSG'
    ELSE name
  END,
  category = 'rwa-treasuries',
  status = 'operating',
  profile = json_set(
    json((SELECT profile FROM _rwa_control_profiles WHERE lower(_rwa_control_profiles.slug) = lower(rwa_depin.slug))),
    '$.sources',
    json((SELECT sources FROM _rwa_control_profiles WHERE lower(_rwa_control_profiles.slug) = lower(rwa_depin.slug)))
  ),
  sources = (SELECT sources FROM _rwa_control_profiles WHERE lower(_rwa_control_profiles.slug) = lower(rwa_depin.slug)),
  updated_at = '2026-08-03'
WHERE lower(slug) IN ('blackrock-buidl', 'ondo-finance');

DROP TABLE _rwa_control_profiles;
